package cmd

import (
	"path"
	"os"
	"log"
	"encoding/json"

	"github.com/spf13/cobra"
)

var exportCmd = &cobra.Command{
	Use:   "export",
	Short: "export JSON to the public/ under the current.",
	Long: `export JSON to the public/ under the current.

This command exports JSON generated by the run command.
JSON is exported to the public/ under the current.
If we do not find the public/, we make it!`,
	Run: export,
}

func export(cmd *cobra.Command, args []string) {
	currentDir, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}

	var jmsDir = path.Join(currentDir, ".tm")
	if f, err := os.Stat(jmsDir); os.IsNotExist(err) || !f.IsDir() {
		log.Fatal("we should run tm init at first")
	}

	var publicDir = path.Join(currentDir, "public")
	if f, err := os.Stat(publicDir); os.IsNotExist(err) || !f.IsDir() {
		if err := os.Mkdir(publicDir, 0777); err != nil {
			log.Fatal(err)
		}
	}

	var sampleJSON = path.Join(publicDir, "sample.json")
	file, err := os.Create(sampleJSON)
    if err != nil {
		log.Fatal(err)
    }
    defer file.Close()

	json, err := json.Marshal(template)
	if err != nil {
		log.Fatal(err)
    }
    file.Write(([]byte)(json))
}

func init() {
	rootCmd.AddCommand(exportCmd)
}
