project_name: tuna
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    id: uncompressed
    binary: tuna
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
      - -X github.com/solaoi/tuna-mayonnaise/cmd.version={{.Version}}
      - -X github.com/solaoi/tuna-mayonnaise/cmd.commit={{.FullCommit}}
      - -X github.com/solaoi/tuna-mayonnaise/cmd.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - netbsd
      - openbsd
      - dragonfly
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: 386
  - main: .
    id: compressed
    binary: tuna
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
      - -X github.com/solaoi/tuna-mayonnaise/cmd.version={{.Tag}}
      - -X github.com/solaoi/tuna-mayonnaise/cmd.commit={{.FullCommit}}
      - -X github.com/solaoi/tuna-mayonnaise/cmd.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
    hooks:
      post: upx --lzma '{{ .Path }}'

archives:
  - 
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
brews:
  -
    name: tuna
    tap:
      owner: solaoi
      name: homebrew-tap
    url_template: "https://github.com/solaoi/tuna-mayonnaise/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: mail@aota.blog
    homepage: "https://github.com/solaoi/tuna-mayonnaise"
    description: "Software to generate and serve JSON/HTML on the node-based editor"
    license: "MIT"
    test: |
      system "#{bin}/tuna help"
    install: |
      bin.install "tuna"
