project_name: tuna
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    id: uncompressed-darwin
    binary: tuna
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
      - -X github.com/solaoi/tuna-mayonnaise/cmd.version={{.Version}}
      - -X github.com/solaoi/tuna-mayonnaise/cmd.commit={{.FullCommit}}
      - -X github.com/solaoi/tuna-mayonnaise/cmd.date={{.Date}}
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
  - main: .
    id: uncompressed-windows
    binary: tuna
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
      - -X github.com/solaoi/tuna-mayonnaise/cmd.version={{.Version}}
      - -X github.com/solaoi/tuna-mayonnaise/cmd.commit={{.FullCommit}}
      - -X github.com/solaoi/tuna-mayonnaise/cmd.date={{.Date}}
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
  - main: .
    id: compressed-linux
    binary: tuna
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
      - -X github.com/solaoi/tuna-mayonnaise/cmd.version={{.Tag}}
      - -X github.com/solaoi/tuna-mayonnaise/cmd.commit={{.FullCommit}}
      - -X github.com/solaoi/tuna-mayonnaise/cmd.date={{.Date}}
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post: upx --lzma '{{ .Path }}'

archives:
  - 
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
release:
  prerelease: auto
brews:
  -
    name: tuna
    tap:
      owner: solaoi
      name: homebrew-tap
    url_template: "https://github.com/solaoi/tuna-mayonnaise/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: mail@aota.blog
    homepage: "https://github.com/solaoi/tuna-mayonnaise"
    description: "Software to generate and serve JSON/HTML on the node-based editor"
    license: "MIT"
    test: |
      system "#{bin}/tuna help"
    install: |
      bin.install "tuna"
