name: go deps scan

on:
  schedule:
    - cron: "0 3 * * *" # 毎日の正午に実行 ( 12+JST = 3+UTC )
  workflow_dispatch:
    branches:
      - main

defaults:
  run:
    working-directory: ./command

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 1.x in order to write go.list file
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.0
      - name: WriteGoList
        run: go list -json -deps > ../go.list

      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main
        with:
          nancyCommand: sleuth --loud
