name: goreleaser

on:
  release:
    types:
      - published

defaults:
  run:
    working-directory: ./ui

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: OSXCross for CGO Support
        run: |
          pwd
          mkdir ../../osxcross
          git clone https://github.com/plentico/osxcross-target.git ../../osxcross/target

      - name: Downgrade libssl
        run: |
          echo 'deb http://security.ubuntu.com/ubuntu bionic-security main' | sudo tee -a /etc/apt/sources.list
          sudo apt update && apt-cache policy libssl1.0-dev
          sudo apt-get install libssl1.0-dev

      - name: Install compiler for windows
        run: |
          sudo apt install gcc-mingw-w64

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.X'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - run: npm ci
      - run: npm run vite-build
      - run: mv dist/* ../command/cmd/static/

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
          workdir: ./command/
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
