name: goreleaser

on:
  release:
    types:
      - published

defaults:
  run:
    working-directory: ./ui

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.16.0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - run: npm ci
      - run: npm run build
      - run: mv build/* ../command/cmd/static/

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
          workdir: ./command/
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
