name: goreleaser

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

defaults:
  run:
    working-directory: ./ui

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.16rc1

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.x'

      - run: npm ci
      - run: npm run build
      - run: mv build/* ../command/cmd/static/

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
          workdir: ./command/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
