name: TOC Generator

on:
  push:
    branches:
      - main
    paths:
      - 'README*.md'

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/toc-generator@v3
        with:
          MAX_HEADER_LEVEL: 3
          FOLDING: true
          TOC_TITLE: 'CLICK'
